### ISSUE TITLE
Set up Whisper AI app

### ISSUE THREAD

**Issue by ninanorgren** [SciLifeLab-TrainingHub-Platform/TeSS#100]
**As a** course leader  
 **I need** to be able to generate transcripts and srt files to my videos  
 **So that** I can use the videos in my Training  
   
 ### Details and Assumptions
 * It should require no installation and be compatible with all OSes
* It should be free
* It should be accessible for non-technical people
   
 ### Acceptance Criteria  
   
 ```gherkin
Given the user is on the whisper app website  
When they upload a video and press Transcribe  
Then a file with the transcribed text will be downloaded  
 ```

 ```gherkin
Given the user is on the whisper app website  
When they upload a video and press Generate .srt file  
Then a .srt file with the transcribed text should be downloaded  
 ```

**Comment by harshita3199** [comment]
It generates the transcript at present. We need to work on srt files generation. We need to handle concurrency and safety features in the flask app

**Comment by harshita3199** [comment]
Done and deployed on Serve. Later the plan could be to host it as a separate service on k8s  if needed but we will see later
