### ISSUE TITLE
Modify city field on events page to similar field like venue

### ISSUE THREAD

**Issue by harshita3199** [SciLifeLab-TrainingHub-Platform/TeSS#106]
- create city field similar like venue

- Also, check for venue field in the events page, it is missing in the filter section.

<img width="404" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnEwQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2cdbc9a8d3daff0b01556537f764bd05dcf98771/image.png" alt="image.png" />

**Comment by adeel-ahmad-awan** [comment]
PR https://github.com/SciLifeLab-TrainingHub-Platform/TeSS/pull/141
