### ISSUE TITLE
Fine tuning the UI design for next release

### ISSUE THREAD

**Issue by harshita3199** [SciLifeLab-TrainingHub-Platform/TeSS#138]
- change scilifelab logo dimensions for small screen at footer
- Courses & Community image width for small screen
- about page on team section, image html issue on col md 3 and also text issue in kristen's image
- about page, header image is not resizing
- about page, bottom image is not resizing
- about page, educational science work text is getting overwritten on the images
- our resources image repeating in top section for small screen
- our resources empty space on map image on small screen
- pedagogic-support image not resizing
- the cal.com iframe is now left aligned, it should be centre aligned
- the bicycle principles for short form training card content is outside of its box in the training assets page. -- first test this that it is going out of the box or not in your case
- the text on the cards for training assets all have underlines now (they didn't on the guides page thats up currently)<img width="484" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnUwQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d2dec2426bbff523bf2c96ea9fd9c75e951ae47a/Screenshot%202024-07-04%20at%2012.44.39.png" alt="Screenshot 2024-07-04 at 12.44.39.png" />
- <img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjIwQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ea0fd94e6364735defb181f0309d5cbb594927eb/image.png" alt="image.png" />

**Comment by adeel-ahmad-awan** [comment]
fixes done

- added animation on flash message
- text center and alignment for footer
- Courses & Community page image width 100%
- header logo image resizing on small screen 
- about page researchbox responsive issue resolution

**Comment by adeel-ahmad-awan** [comment]
https://github.com/SciLifeLab-TrainingHub-Platform/TeSS/pull/153
