### ISSUE TITLE
need to debug how disabled event works and also why future events went in there?

### ISSUE THREAD

**Issue by harshita3199** [SciLifeLab-TrainingHub-Platform/TeSS#150]
There is a field in admin console Event section
named as scraper record, when I checked it to :white_check_mark: then it is now visible in events page in preprod

**Comment by adeel-ahmad-awan** [comment]
@harshita3199 after discussion with @kristen-schroeder , we found out that for the event are not visible all we need is to  

- change visibility to false 
- save event
- change visibility to true
- save the event

after that the events will be visible on course page

**Comment by harshita3199** [comment]
Are we good with the current code base to release on the production then? @adeel-ahmad-awan 
If yes, then I can close this issue
