### ISSUE TITLE
check why events url check is failing

### ISSUE THREAD

**Issue by adeel-ahmad-awan** [SciLifeLab-TrainingHub-Platform/TeSS#154]
## Acceptance Criteria
> Generated by [Zenhub AI](https://www.zenhub.com/ai)

 - [ ] **Scenario: Checking why events URL check is failing**
  - Given a schedule task runs at 6 AM daily
  - When the task checks the events URLs
  - Then the task should identify and report any failures in the pre-production environment, even if the URLs are working in other environments

**Comment by adeel-ahmad-awan** [comment]
I have manually executed the `tess:check_resource_urls` command in my local environment, and I did not encounter any issues with the code. All links are functioning correctly.

Additionally, I have updated the event URLs to match one from our pre-production environment.

Based on the pre-production message:

> TeSS has been unable to access this event's URL since 20 July 2024 - the page may have been moved.

I suspect that the scheduled commands are not running properly. These commands are supposed to execute every day at 6 AM, according to the configuration:


```
dead_link_check:
  every: day
  at: 6am
```

**Comment by kristen-schroeder** [comment]
Is it related that when the URLs are added in the first place, this error is shown? Possibly not, but here is this information :)

<img width="788" alt="Screenshot 2024-08-02 at 09 12 02" src="https://github.com/user-attachments/assets/d5076607-84f2-4d20-bab9-7431f0250135">

**Comment by adeel-ahmad-awan** [comment]
as per out latest finding, the issue seems to be server side issue where the server is blocking the outgoing requests, which is causing url check fails.

**Comment by harshita3199** [comment]
Tested out in pre-production,issue was related to network policies denied by default, working fine, need to read more to make changes in production about security
