### ISSUE TITLE
Enable the providers on the top panel 

### ISSUE THREAD

**Issue by harshita3199** [SciLifeLab-TrainingHub-Platform/TeSS#171]
- content providers need to have one to many relationaship so we could select multiple providers in the events creation page. like its a collaborative effort from NBIS and Training Hub

- Enable it on the top panel then

**Comment by adeel-ahmad-awan** [comment]
PR: https://github.com/SciLifeLab-TrainingHub-Platform/TeSS/pull/177

**Comment by harshita3199** [comment]
Feature is created and PR is created in the github but @adeel-ahmad-awan is working on the test cases related to the content provider.

**Comment by adeel-ahmad-awan** [comment]
make sure to disable nodes from system<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1U1Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--33b6b9822a3657d2d07ab58523eb25dc3e1d8d25/image.png" alt="image.png" />

**Comment by harshita3199** [comment]
PR is merged in rc-1.3.1. we have disabled the node as well.
