### ISSUE TITLE
Need to implement the city field again to separately search for events

### ISSUE THREAD

**Issue by harshita3199** [SciLifeLab-TrainingHub-Platform/TeSS#172]
Right now, we have the city field in the app which is creating all the cities per event as a new search in the filter section, we don't want to have this, Instead, when a user clicks on Lund, all the events should pop up in the result section.

**Comment by adeel-ahmad-awan** [comment]
https://github.com/SciLifeLab-TrainingHub-Platform/TeSS/pull/176

**Comment by adeel-ahmad-awan** [comment]
@harshita3199 
**note:** after deployment we need to re-index the solr searchable by running the following command 
`bundle exec rake sunspot:reindex`
