### ISSUE TITLE
Disable the automatic registration page in events

### ISSUE THREAD

**Issue by harshita3199** [SciLifeLab-TrainingHub-Platform/TeSS#174]
<img width="916" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenZkQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f9217fc095c9d63d3f3843f11dbed828f00e09b7/image.png" alt="image.png" />

We can keep the info section of What are events? and remove last 2 para from that
Instead of locking field section, we can have "How do events word?"   --- @kristen-schroeder could provide some text for this

**Comment by harshita3199** [comment]
If we are enabling the scraper then we should enable the route for the registration otherwise, remove the text
Just a note adding:
We have also removed the lock fields from title and URL because we are not using the scrapers and automatic registration thing.

**Comment by kristen-schroeder** [comment]
Text:

**How do events work?**
Fill in all required fields of this form to register an event on the Training Portal. 

Provide detailed information: people browsing need to know what they will learn and who to contact with questions. 

Once you click 'Add Event', your event will be sent for moderation. You will see your event in your profile, and are able to edit your event up until it is approved or rejected by our admin team.

**Comment by umunixie** [comment]
The text above doesn't fit the 'Edit Event' page's spirit (it doesn't have 'Add Event' to click, it might or might not trigger approval depending on the trust level of the user and the approval state of the event) so for that page Kristen and i agreed to just remove the helper sidebar text entirely.
