### ISSUE TITLE
enable login + new user account creation (TeSS infrastructure)

### ISSUE THREAD

**Issue by kristen-schroeder** [SciLifeLab-TrainingHub-Platform/TeSS#179]
if i am a new user
and i visit the training portal
i can create an account that is registered in the database

if i am an existing user
and i visit the training portal
i can click a link to visit the login page and log in

**Comment by kristen-schroeder** [comment]
LS-Login - do we need to register? does it work straight out of the box?

we should do similar to DC nextcloud - google
this is a new feature - should we diverge? waiting on information before deciding

for now, we use what is already in TeSS 

for now: Username and Password login

**Comment by adeel-ahmad-awan** [comment]
PR: https://github.com/SciLifeLab-TrainingHub-Platform/TeSS/pull/195
