### ISSUE TITLE
Enable node in the portal

### ISSUE THREAD

**Issue by harshita3199** [SciLifeLab-TrainingHub-Platform/TeSS#184]
We just want it to be enable it that it is hidden from the user and we would be able to add scilifelab logo(as node) to the events.

**Comment by kristen-schroeder** [comment]
enabling scilifelab event as a node should allow us to gate events that populate the SciLifeLab wordpress calendar

**Comment by adeel-ahmad-awan** [comment]
PR: https://github.com/SciLifeLab-TrainingHub-Platform/TeSS/pull/196




As per discussion

- node should be enable but the user shouldn't see it on navbar and also cannot go to the node page
- in event create and edit page, the node association should be there which will associate the node to event(in our case there will be only one node)

**Comment by harshita3199** [comment]
@kristen-schroeder input required
1. What is the name of node we should have instead of Sweden(existing)?   SciLifeLab Training???
2. Which image we should use to point it to, it will be visible on each events associated with Scilifelab Training, right now it points to elixir logo so should we use our logo?
3. We need to change the field name in the content provider? Should we just say Node or something else or any other idea<img width="1856" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGx1Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--113a56f0377f234b0380e2997a35e7236d2e3dbe/image.png" alt="image.png" />

**Comment by kristen-schroeder** [comment]
@harshita3199 
1. the name of the node should be SciLifeLab
2. are there dimensions restrictions? its preferrable to use the scilifelab logo, but if it is distorted, we can use the symbol---green symbol and it should be on right align
3. Disable node in the content provider. 
4. Disable node show page and it should be unclickable from the event page
5. In the event add form, we should have a dropdown/radio button with Scilifelab and External
6. Remove Node Heading form the event page

**Comment by adeel-ahmad-awan** [comment]
@harshita3199 i have updated the PR, I have added the external node as a node in the DB and for simplification i have removed the connection after saving the record. now it is working as expected

**Comment by adeel-ahmad-awan** [comment]
I have added a custom command for creation of Nodes

`bin/rails node:create_entries`

this command creates the nodes for association with event if the nodes are already not present in DB. The nodes are created with the admin user as the creator and have predefined names and slugs. These predefined values will be used throughout the application for node validation.

**Comment by harshita3199** [comment]
@adeel-ahmad-awan the sweden node which is already present in the db should also be deleted otherwise after running the script we have 3 nodes
<img width="812" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0dWQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--11b4f8dbc324425fdca28dd521d944344f2299c4/image.png" alt="image.png" />

**Comment by adeel-ahmad-awan** [comment]
Updated PR: https://github.com/SciLifeLab-TrainingHub-Platform/TeSS/pull/269
