### ISSUE TITLE
Send the event request to admin to approve and reject through admin console

### ISSUE THREAD

**Issue by harshita3199** [SciLifeLab-TrainingHub-Platform/TeSS#187]
We need to have a dropdown field with options as approve, reject and changes requested from user

**Comment by adeel-ahmad-awan** [comment]
PR: https://github.com/SciLifeLab-TrainingHub-Platform/TeSS/pull/194

<img width="1619" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3RlQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5eaf425616eb6db068f8c5e1116ab7c932d0029d/image.png" alt="image.png" />
