### ISSUE TITLE
Backend changes for all users related to event

### ISSUE THREAD

**Issue by harshita3199** [SciLifeLab-TrainingHub-Platform/TeSS#190]
- All Users should be able to see only all the published events 
- Each user should see published events + the unmoderated event which he/she has created with different colour coding (KRISTEN WOULD BE HELPING HERE FOR THE COLOUR CODE (small coloured icon in the corner, green for approved, red for declined , yellow for pending)---adding a icon that shows the event status on hovering over it.
- User can edit the event as much as they want before and after it has been moderated.

**Comment by adeel-ahmad-awan** [comment]
https://scilifelab.atlassian.net/wiki/spaces/TI/pages/3183640604/Workflows

**Comment by adeel-ahmad-awan** [comment]
pre/post deployment tasks

- change the event status of all the already published events
- change the approved_events_count in user table grater then 3, can write a script to calculate that.  
- add trueted user in DB

**Comment by adeel-ahmad-awan** [comment]
PR: https://github.com/SciLifeLab-TrainingHub-Platform/TeSS/pull/204

Need to change the time interval for cronjob, currently it will run after every 5.minutes

**Comment by harshita3199** [comment]
whenever --update-crontab.   execute this command to register the cronjob for testing it.

**Comment by harshita3199** [comment]
crontab -l is the command to see the registered cronjob

**Comment by harshita3199** [comment]
changes while testing the ticket which we have not discussed earlier. 
After the user makes the changes as per requested in the email from STO, then we have not discussed this case internally, but ideally it should send the mail to traininghu@scilifelab.se (admin) that changes are submitted by user, please review and status should change to awaiting_review.
If the event is approved by the admin then,approved mail should include published and it should be separate from the event submitted mail.
PLease check the document attached https://docs.google.com/document/d/14-aK-1wg2slfMowT82Q2jJddqSv6lF7xHnGQde3DvYQ/edit?tab=t.0

**Comment by harshita3199** [comment]
tested on dev, working fine. Just added the finding in the testing doc
Will try to test it in pre prod as well

**Comment by harshita3199** [comment]
tested on dev, working fine. Just added the finding in the testing doc
Will try to test it in pre prod as well

**Comment by harshita3199** [comment]
tested the ticket in pre-prod as well, everything is working fine (functionalities)
two things been addressed in the review meeting which were: 
the event status should not be visible on the published events.
making the fields mandatory as per kristen's image or description
Email footer image needes to be implemented
remove the optional keyword in admin console from the event status though it is non nullable field in db(tested)

**Comment by harshita3199** [comment]
PR is merged after testing the new updates related to email templates
