### ISSUE TITLE
Content provider image upload issue related to resizing

### ISSUE THREAD

**Issue by harshita3199** [SciLifeLab-TrainingHub-Platform/TeSS#192]
When I uploaded an image of random size then it popped up. My question is are we handling it better for user perspective in UI and also are we sharing this info to the user that your image size should be this much so that they will only upload. image of that size. I have uploaded below image
<img width="419" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDFkQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ec8987b2710311436af6ce38ea046618ad8cce54/glittr.png" alt="glittr.png" />

<img width="1266" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHBkQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--600e4a1d9815d8f53915cee998e00040a0a6c6bf/image.png" alt="image.png" />

**Comment by harshita3199** [comment]
Maybe the image is broken here but still we should check is there any restriction on size and if yes then how are we handling it for user

**Comment by adeel-ahmad-awan** [comment]
PR: https://github.com/SciLifeLab-TrainingHub-Platform/TeSS/pull/201

i have added the error handling and this is how it looks with new code
<img width="1370" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXVJQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e8d1e12cb8c2a3d6a1dd776c4f69fb463b681cae/image.png" alt="image.png" />
