### ISSUE TITLE
Captcha addition in the sign up page

### ISSUE THREAD

**Issue by harshita3199** [SciLifeLab-TrainingHub-Platform/TeSS#197]
- start with your own key and harshita will explore creating key with traininghub account

**Comment by adeel-ahmad-awan** [comment]
## Configuring Google reCAPTCHA in `secrets.yml`

Our code already supports Google reCAPTCHA, so all that’s needed is to add the reCAPTCHA keys to `secrets.yml`.

### Steps to Add Google reCAPTCHA Keys


1. **Generate reCAPTCHA Keys**:
   To generate the keys, visit the [Google reCAPTCHA site](https://cloud.google.com/recaptcha/docs/create-key-website) and follow these steps:

   - Click on **Go to reCAPTCHA Admin Console**.
   - On the next page:
     - Enter a **label** (e.g., your site name).
     - Select **reCAPTCHA v2** and **Challenge: Verify requests with a challenge**.
     - Choose the **"I'm not a robot" Checkbox** option.
     - Add domains for all environments (e.g., localhost, dev, pre-production, production).
     - Include Google Cloud Platform if necessary.

2. **Copy the Keys**:
   - After configuration, copy the **site key** and **secret key** and paste them into `secrets.yml` under the `recaptcha` section.

Refer to the screenshot for additional guidance on completing these steps.

<img width="351" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3AvQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3402a854c38aeb7171649ffb57fdf7a850386ab7/image.png" alt="image.png" />
<img width="832" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3QvQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--539fae4f9984a3bd2fbd7b3055e173ec67819746/image.png" alt="image.png" />
<img width="1384" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3gvQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5f61f425d53fff03b81a36578fb77f32211e7e4e/image.png" alt="image.png" />

**Comment by adeel-ahmad-awan** [comment]
<img width="775" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFYvQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a04ebdaf44206cd739b736686c0a0516a9894b78/image.png" alt="image.png" />

**Comment by harshita3199** [comment]
I have done the setup of reCAPTCHA in the signup page. Created the documentation on confluence
