### ISSUE TITLE
Email footer image needs to be implemented for end user emails

### ISSUE THREAD

**Issue by harshita3199** [SciLifeLab-TrainingHub-Platform/TeSS#213]

**Comment by kristen-schroeder** [comment]
![emailfooter](https://github.com/user-attachments/assets/e767807e-44d4-4763-adea-93a0574bb18d)

image for email footer @harshita3199

**Comment by adeel-ahmad-awan** [comment]
PR: https://github.com/SciLifeLab-TrainingHub-Platform/TeSS/pull/218

**Comment by adeel-ahmad-awan** [comment]
<img width="846" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1BvQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6c9486039ab091b7688b4e837db35b8173998a91/image.png" alt="image.png" />
<img width="935" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1hvQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fd5119a23842435722df2adfd80dc3f54ab6498f/image.png" alt="image.png" />
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2JvQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--85d4f7d455bdf0831d0358c1413d06036be5e968/image.png" alt="image.png" />
<img width="983" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2ZvQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4c769a8479eada27d0f6d7be24b78a120fa98d95/image.png" alt="image.png" />
