### ISSUE TITLE
Display tools and resources on Portal

### ISSUE THREAD

**Issue by ninanorgren** [SciLifeLab-TrainingHub-Platform/TeSS#57]
**As a** Trainer  
 **I need** to easily find all the resources and technical resources that TH offer, on the Portal  
 **So that** I can upskill myself, or take advantage of the resources offered in my own training  
   
 ### Details and Assumptions
 * 
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given [some context]
 When [certain action is taken]
 Then [the outcome of action is observed]
 ```

**Comment by harshita3199** [comment]
Covered by already existing issues for nextcloud #64 and shiny-certificate #50 from shiny board.
Just reorganising existing resources as well along with these.

**Comment by kristen-schroeder** [comment]
see comment https://github.com/SciLifeLab-TrainingHub-Platform/TeSS/issues/64#issuecomment-2129866040 for updated design

**Comment by harshita3199** [comment]
Done and released it on the portal. Hence, closing the user story
