### ISSUE TITLE
Design on how to display it on portal

### ISSUE THREAD

**Issue by harshita3199** [SciLifeLab-TrainingHub-Platform/TeSS#64]
Release Nextcloud storage for training materials: #58

**Comment by kristen-schroeder** [comment]
Kristen's question: is it okay to reorganize the our resources page?
Nina, product owner: yes!

**Comment by kristen-schroeder** [comment]
Hi all -- here is the resources redesign page. What do we think?

If it passes the product owner's test, I will add design for sub-pages :)

[resources-redesign-KSmay20.pdf](https://github.com/SciLifeLab-TrainingHub-Platform/TeSS/files/15378468/resources-redesign-KSmay20.pdf)

**Comment by ninanorgren** [comment]
I like the design of the resources page, especially with the word cloud picture that makes it easier to see examples of what is in there. The only thing I'm thinking about is the Community page. I'm not sure it's obvious to anyone visiting the page looking for information for Train-the-Trainer courses that this is the page they should look at. Maybe we should call it Community & Training, or something similar?

For the subpages I'm thinking we should keep the Support page clean, and just have our own services there. For the Community page we could then have our own trainings (courses and seminars), and a section with other resources we endorse

**Comment by kristen-schroeder** [comment]
basic design changes with assets available as branch kristen_resources_redesign

There was a request from Jessica to rename 'Tools & Guides' to 'Resources'. We can discuss the naming further :)

**Comment by kristen-schroeder** [comment]
update: redesign expanded to include subpages.

[resources-redesign-may24KS.pdf](https://github.com/SciLifeLab-TrainingHub-Platform/TeSS/files/15436880/resources-redesign-may24KS.pdf)
