### ISSUE TITLE
Development work to display it on portal + testing

### ISSUE THREAD

**Issue by harshita3199** [SciLifeLab-TrainingHub-Platform/TeSS#65]
Release Nextcloud storage for training materials: #58

**Comment by kristen-schroeder** [comment]
commented .pdf of design changes for pages.

The support page will stay the same (pedagogic support becomes support!)

[resources-redesign-update.pdf](https://github.com/SciLifeLab-TrainingHub-Platform/TeSS/files/15470146/resources-redesign-update.pdf)

**Comment by adeel-ahmad-awan** [comment]
[PR link](https://github.com/SciLifeLab-TrainingHub-Platform/TeSS/pull/136)
