### ISSUE TITLE
Redeveloping Courses Page

### ISSUE THREAD

**Issue by harshita3199** [SciLifeLab-TrainingHub-Platform/TeSS#72]
**As a** Course organizer 
 **I need** to be able to easily select timezone, venue, and organizer when adding courses to the portal  
 **So that** it will be faster and easier for me, and avoids duplications of venues and organizers when searching on the portal  
   
 ### Details and Assumptions
 * Currently the default time zone is set to Brussels, this should be changed to Stockholm
 * Field for organizer is freetext, this should be a dropdown connected to the organizer table in the db. If the organizer is not present in the dropdown list, they first have to add a new organizer on the Organizer page
 * Field for venue is freetext, and part of the course table in the db. Change this so the venue is a separate table in the db, and have a dropdown for selecting venues in the register course form. Users should be able to add their own venues if it does not exist in the dropdown, which will then create a new venue entry in the db. This would require linking the venue table to the course table in the db
 * We need a migration script for migrating the db for this
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the user is on the create course page
 When they scroll down to the timezone field
 Then they should see the default timezone of Stockholm
 ```

 ```gherkin
 Given the user is on the create course page
 When they click on the venue field
 Then they should get a dropdown with all venues in the db to select from,
 And if their venue is not listed, a freetext field to create a new venue will be displayed
 ```

 ```gherkin
 Given the user is on the create course page
 When they click on the organiser field
 Then they should get a dropdown with all organisers in the db listed,
 And if their organiser is not listed, a button to redirect them to create organiser
 ```

**Comment by kristen-schroeder** [comment]
I have gone through the add course form and made some suggestions on what we should remove to make it easier for course instructors to add their courses without being overwhelmed. see the attached .pdf! 

[fieldguideforadeel.pdf](https://github.com/SciLifeLab-TrainingHub-Platform/TeSS/files/15305685/fieldguideforadeel.pdf)

**Comment by harshita3199** [comment]
Select venue option is getting selected as a venue in the dropdown.
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVViQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6f230ddf9d0ad282cc6909130da244739647eb5a/image.png" alt="image.png" />

**Comment by harshita3199** [comment]
Events should be visible including the  last date on the events page rather than past events.

**Comment by adeel-ahmad-awan** [comment]
PR link for this task
https://github.com/SciLifeLab-TrainingHub-Platform/TeSS/pull/99

**Comment by harshita3199** [comment]
Tested the PR, just keeping the record for the test cases: 
1070 tests, 5512 assertions, 6 failures, 3 errors, 10 skips
