### ISSUE TITLE
Setup the openEDx on local and test it out

### ISSUE THREAD

**Issue by harshita3199** [SciLifeLab-TrainingHub-Platform/TeSS#80]
This is the link to follow https://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/installation/  and decide which approach works best for us to install the platform.

- We need to customise the platform according to our needs and also want to pull the changes from the actual open edx repo.
- benefits of different version of openedx to figure out which suits best according to our needs.

**Comment by adeel-ahmad-awan** [comment]
[Untitled document(1).docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2twQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b114a4f2f63c465c3117811e30361bcfa635b644/Untitled%20document%281%29.docx)

**Comment by ninanorgren** [comment]
So it looks like the Tutor setup will be the best option, as it is the easiest, but also gives us the possibility of customizing the platform by changes in the code
