### ISSUE TITLE
Talk to operations office for the integration of events to scilifelab.se

### ISSUE THREAD

**Issue by harshita3199** [SciLifeLab-TrainingHub-Platform/TeSS#84]
We need to talk to operations office for getting the consent for automating it with scilifelab static site calendar to update the events from portal

Belongs to [user story](https://github.com/SciLifeLab-TrainingHub-Platform/TeSS/issues/55)

**Comment by kristen-schroeder** [comment]
data centre owns the SciLifeLab WP site
can they maintain it for us?

can we get a copy of the website in a docker? maybe

**Comment by kristen-schroeder** [comment]
talk to operations office about routines
talk to DC about how to technically do the plugin

**Comment by harshita3199** [comment]
Integration planning doc: [check here](https://docs.google.com/document/d/1EEFA3VVfkP3bdSb4-_DqUi_xDa6lVdSTyRrO_iuvQAA/edit)

**Comment by harshita3199** [comment]
Update from Nina:
Hi team
Me and Kristen just had a meeting with the persons in charge at DC and OO, so now we finally have a decision about the integration with the scilifelab website :slightly_smiling_face: We agreed that the users should be directed to the portal when they want to add courses, and we will use our trusted user system to add things to the portal. They were sceptical to an API at this point, both because they thought the plugin api on their side was not secure enough, and that they are pretty soon doing major changes to the website. Which is fair enough. So what will happen when an event is published on our portal, is that is will send an automatic email to the education mail at scilifelab, and someone there will manually update the calendar, or any changes. Once DC has done their updates to the website, they should have a better system of automatically interacting with it, and then we can connect it to be fully automatic.
Me and Kristen both think this is a good solution, and everyone seemed seemed happy with re-directing the users to the portal. We will need to coordinate this further with Maria at OO, but from our perspective we go ahead as planned

**Comment by harshita3199** [comment]
Next Step: Look forward to setup a meeting with Maria related to the fields for event form
Discussion: We present our event form field and get the scilifelab web team inputs....(after New Year)
