### ISSUE TITLE
Create a Email Template for the confirmation mail when a user signs up on portal

### ISSUE THREAD

**Issue by harshita3199** [SciLifeLab-TrainingHub-Platform/TeSS#91]

**Comment by harshita3199** [comment]
**This is for Forgot Password**
<img width="1433" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1JEQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5307b65d486d232ec4e4b11cf9dd801679d84cbf/image.png" alt="image.png" />



**This is for signup confirmation email**
<img width="1294" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0pEQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6c015de893106f1bebae22e8b0bf5ec9d95fbe52/image.png" alt="image.png" />

**Comment by kristen-schroeder** [comment]
@adeel-ahmad-awan 

1. This is for signup confirmation email

[template-confirm.zip](https://github.com/user-attachments/files/17522811/template-confirm.zip)

2. This is for forgot password:
[passwordreset.zip](https://github.com/user-attachments/files/17522927/passwordreset.zip)

If you have any trouble opening these files -- I have also emailed them to you! :)
